t_test/urls.py
from django.urls import path,re_path
from t_test import views

#TEMPLATE TAG IMPORTANTE

app_name="t_test"

urlpatterns = [

    path('usuarios/<int:id>',views.usuarios,name='usuarios'),
    path('add',views.addTarea,name='formulario')

]

telefonica_test/urls.py
from django.contrib import admin
from django.urls import path,include, re_path
from t_test import views as vi

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',vi.index,name='index'),
    path('here/',include('t_test.urls'),name='usuarios'),
    path('form/',vi.addTarea, name='formulario'),
    path('tareasnoc/',vi.tareasnoc, name='tareasnoc'),
    path('calendario/',vi.calendario, name='calendario'),
    path('reporte/',vi.report,name="report"),
    re_path(r'^search/trabajo/$', vi.showTable,name='search'),
    path('buscar/',vi.buscarClientes, name='buscaCliente'),
    re_path(r'^buscar/cliente/$', vi.muestraClientes,name='muestra'),
    path('upload/',vi.upload_file, name='upload'),
    path('calendario_hfc/',vi.calendario_hfc, name='calendario_hfc'),
    re_path(r'^search/trabajo_hfc/$', vi.showTable_hfc,name='search'),
    path('listar/',vi.listar_usuarios, name='listar_usuarios'),
    re_path(r'^listar/fecha/$', vi.showUsuarios,name='showUsuarios'),
    






]

templates/afectados.html
<!DOCTYPE html>

{% extends "base2.html" %}






{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>TELEFONICA</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

    <!-- Include FontAwesome; required for icon display -->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css">

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" crossorigin="anonymous"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" crossorigin="anonymous"
        integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" crossorigin="anonymous"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" crossorigin="anonymous"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"></script>


    <!--  <link rel="stylesheet" href="style2.css"> -->
    <!-- Our Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style2.css' %}">


    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"
        integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous">
    </script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"
        integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous">
    </script>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <!--Chart JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>

    {% block extrahead %}

    {% endblock %}






</head>

<body>

    <div id="header">
        <div id="header-side">
            <button type="button" id="sidebarCollapse" class="btn btn-info" onclick="abrir_cerrar()">
                <i class="fas fa-list-ul"></i>

            </button>



        </div>
        <div id="img">

            <img src=" {% static '/img/logo_verde.png' %} " width="60px" height="50px"> MOVISTAR</div>
    </div>


    <div id="header_s">
        <button type="button" id="sidebarCollapse" class="btn btn-info" onclick="abrir_cerrar()">
            <i class="fas fa-list-ul"></i>

        </button>

    </div>






    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">

            <li>
                <a href="{% url 'index' %}">
                    <div id="img_home"><i class="fas fa-home"></i></div>
                    <div id="home">Home</div>
                </a>

            </li>


            <li>
                <a href="{% url 'buscaCliente'%}">
                    <div id="img_buscarcliente"><i class="fas fa-search"></i></div>
                    <div id="BC">Buscar Cliente</div>
                </a>
            </li>


            <li>
                <a href="{% url 'tareasnoc' %}">
                    <div id="img_tareas"><i class="fas fa-tasks"></i></div>
                    <div id="TN">Tareas NOC</div>
                </a>
            </li>
            <li>
                <a href="{% url 'formulario' %}">
                    <div id="img_formulario"><i class="fas fa-user-check"></i></div>
                    <div id="Form">Form</div>
                </a>
            </li>
            <li>
                <a href="{% url 'calendario' %}">
                    <div id="img_calendario"><i class="fas fa-sun"></i></div>
                    <div id="Calendar">Calendar</div>
                </a>
            </li>
            <li>
                    <a href="{% url 'upload' %}">
                        <div id = "img_upload"><i class="fas fa-cloud-upload-alt"></i></div>
                        <div id="Upload">Upload</div>
                    </a>
                </li>
            <li>
                <a href="{% url 'listar_usuarios' %}">
                    <div id="img_listar_usuarios"><i class="fas fa-user-friends"></i></div>
                    <div id="Lista">Lista usarios</div>
                </a>
            </li>

            <li>
                <a href="{% url 'report' %}">
                    <div id="img_reporte"><i class="fas fa-chart-bar"></i></div>
                    <div id="reporte">Reporte
                    </div>
                </a>

            </li>
            <!--
                <li>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Pages</a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href="#">Page 1</a>
                        </li>
                        <li>
                            <a href="#">Page 2</a>
                        </li>
                        <li>
                            <a href="#">Page 3</a>
                        </li>
                    </ul>
                </li>

                <li>
                    <a href="#">Portfolio</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>

              -->


            <!--
            <ul class="list-unstyled CTAs">
                <li>
                    <a href="https://bootstrapious.com/tutorial/files/sidebar.zip" class="download">Download source</a>
                </li>
                <li>
                    <a href="https://bootstrapious.com/p/bootstrap-sidebar" class="article">Back to article</a>
                </li>
            </ul>
          -->
        </nav>

        <!-- Page Content  -->
        <div id="content">

            {% block content %}

            {% endblock %}


        </div>

        <!-- jQuery CDN - Slim version (=without AJAX) -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
        </script>
        <!-- Popper.JS -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous">
        </script>
        <!-- Bootstrap JS -->
        <!-- jQuery Custom Scroller CDN -->
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js">
        </script>





        <script src="{%static 'script.js'%}"></script>
</body>

</html>

templates/base2.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>TELEFONICA</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

    <!-- Include FontAwesome; required for icon display -->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css">


    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
        integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <!--  <link rel="stylesheet" href="style2.css">
  -->
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"
        integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous">
    </script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"
        integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous">
    </script>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>

    <!--Chart JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>


    {{ form.media }}


    <!-- Our Custom CSS -->



    <link rel="stylesheet" type="text/css" href="{% static 'style2.css' %}">

    {% block head %}

    {% endblock %}




</head>

<body>





    <div id="header">
        <div id="header-side">
            <button type="button" id="sidebarCollapse" class="btn btn-info" onclick="abrir_cerrar()">
                <i class="fas fa-list-ul"></i>

            </button>

        </div>
        <div id="img">

            <img src=" {% static '/img/logo_verde.png' %} " width="60px" height="50px"> MOVISTAR</div>

    </div>

    <div id="header_s">
        <button type="button" id="sidebarCollapse" class="btn btn-info" onclick="abrir_cerrar()">
            <i class="fas fa-list-ul"></i>

        </button>

    </div>







    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">


            <li>
                <a href="{% url 'index' %}">
                    <div id="img_home"><i class="fas fa-home"></i></div>
                    <div id="home">Home</div>
                </a>

            </li>


            <li>
                <a href="{% url 'buscaCliente'%}">
                    <div id = "img_buscarcliente"><i class="fas fa-search"></i></div>
                    <div id="BC">Buscar Cliente</div>
                </a>
            </li>


            <li>
                <a href="{% url 'tareasnoc' %}">
                    <div id = "img_tareas"><i class="fas fa-tasks"></i></div>
                    <div id="TN">Tareas NOC</div>
                </a>
            </li>
            <li>
                <a href="{% url 'formulario' %}">
                    <div id = "img_formulario"><i class="fas fa-user-check"></i></div>
                    <div id="Form">Form</div>
                </a>
            </li>
            <li>
                <a href="{% url 'calendario' %}">
                    <div id = "img_calendario"><i class="fas fa-sun"></i></div>
                    <div id="Calendar">Calendar</div>
                </a>
            </li>
            <li>
                <a href="{% url 'upload' %}">
                    <div id = "img_upload"><i class="fas fa-cloud-upload-alt"></i></div>
                    <div id="Upload">Upload</div>
                </a>
            </li>
            <li>
                <a href="{% url 'listar_usuarios' %}">
                    <div id = "img_listar_usuarios"><i class="fas fa-user-friends"></i></div>
                    <div id="Lista">Lista usarios</div>
                </a>
            </li>

            <li>
                <a href="{% url 'report' %}">
                    <div id = "img_reporte"><i class="fas fa-chart-bar"></i></div>
                    <div id="reporte">Reporte
                    </div>
                </a>

            </li>
            <!--
                <li>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Pages</a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href="#">Page 1</a>
                        </li>
                        <li>
                            <a href="#">Page 2</a>
                        </li>
                        <li>
                            <a href="#">Page 3</a>
                        </li>
                    </ul>
                </li>

                <li>
                    <a href="#">Portfolio</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>

              -->
            </ul>

            <!--
            <ul class="list-unstyled CTAs">
                <li>
                    <a href="https://bootstrapious.com/tutorial/files/sidebar.zip" class="download">Download source</a>
                </li>
                <li>
                    <a href="https://bootstrapious.com/p/bootstrap-sidebar" class="article">Back to article</a>
                </li>
            </ul>
          -->
        </nav>

        <!-- Page Content  -->
        <div id="content">





            {% block content %}

            {% endblock %}

        </div>
    </div>

    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
        integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous">
    </script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
        integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous">
    </script>
    <!-- jQuery Custom Scroller CDN -->
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js">
    </script>



    {% block fin %}

    {% endblock %}

    <script src="{%static 'script.js'%}"></script>

</body>

</html>

templates/buscaCliente.html
<!DOCTYPE html>

{% extends "base2.html" %}

{% block extrahead %}
{{ form.media }}
{% endblock %}

{% load crispy_forms_tags %}
{% block content %}

<div id = "cliente_content">

<div class="row">
  <div class="col-md-4">

    <form  action="/buscar/cliente" method="GET" >
      {{form|crispy}}
      <!--<button type="submit" class="btn btn-primary">Submit</button>-->
      <button type="submit" class="btn btn-success">
    <i class="icon-circle-arrow-right icon-large"></i> Buscar
  </button>
    </form>
  </div>
</div>

<h2></h2>
<h2>TAREAS </h2>
<div class="row">
  <div class >
    {%if tarealist%}
      <table class="table table-hover table-stripped">
        <thead>
          <th>Usuario</th>
          <th>Trabajo programado(CRQ)</th>
          <th>Elemento de red afectado </th>
          <th>Duración(hh:mm:ss)</th>
          <th>Fecha de Corte </th>
        </thead>

      {%for t in tarealist %}
        {%for c in cliente%}
      <tr>
        <td>{{c.codigoCliente}}</td>
        <td>{{t.infoPlanta.remedy}}</td>
        <td>{{t.infoPlanta.troba.trobaNombre}}</td>
        <td>{{t.duration}}</td>
        <td>{{t.fecha}}</td>


      </tr>
        {%endfor%}
      {% endfor %}

    </table>
    {% else %}

    <p> No hay informacion que mostrar </p>

    {%endif%}

  </div>
</div>


<button
      type  = "submit" name = "report" class="btn btn-success" > <i class="icon-circle-arrow-right icon-large"></i> Reporte de usuario
</button>



  <canvas id = "myChart">

  </canvas>

</div>
{% endblock %}

templates/calendario.html
<!DOCTYPE html>

{% extends "base2.html" %}

{% load crispy_forms_tags %}
{% crispy form  form.helper%}

{% block head %}



<!-- CALENDARIO
-->
<!-- Import Google Icon Font -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />

<!-- Import materialize.css
-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />

<link type="text/css"  rel="stylesheet" href="css/materialize.min.css" media="screen,projection">
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
crossorigin="anonymous"></script>

<!-- Let browser know website is optimized for mobile -->
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<style>
    body{
        background-color: #B6DBFF;
    }
    #date{
        margin-top: 50px;
    }
</style>

{% endblock %}

{% block content %}

<div id = "calendario_content">

  <div class="row">
    <div class="col-md-4">
        <h5>Ingrese fecha deseada</h5>
        <form action="/search/" method="GET">
            <input  placeholder='Haga click aquí' type="text" id="date" class="datepicker" name="fecha">

            <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                <i class="material-icons right">send</i>
            </button>
        </form>
    </div>
  </div>



  <h2>TAREAS NOC</h2>
  <div class="row">
    <div class >
      {%if tarealist%}
        <table class="table table-hover table-stripped">
          <thead>
            <th>Remedy</th>
            <th>Resumen </th>
            <th>Fecha de Inicio</th>
            <th> Responsable</th>
          </thead>

        {%for u in tarealist %}
        <tr>
          <td>{{u.remedy}}</td>
          <td>{{u.resumen}}</td>
          <td>{{u.fechaHoraInicio}}</td>
          <td>{{u.responsable}}</td>

        </tr>
        {% endfor %}

      </table>
      {% else %}

      <p>no hay informacion que mostrar </p>

      {%endif%}

    </div>
  </div>

</div>

{% endblock %}


{% block fin %}


<!-- script calendario -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<!-- JavaScript at end of body for optimized loading -->
<script type="text/javascript">
    const Calendar = document.querySelector('.datepicker');
        M.Datepicker.init(Calendar, {
            autoClose: true,
            format: 'yyyy-mm-dd',
            setDefaultDate: false,
            defaultDate: new Date(2019, 1, 1),
            minDate: new Date(1990, 1, 1),
            maxDate: new Date(2030, 1, 1),
            i18n: {
                months: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Setiembre', 'Octubre', 'Noviembre', 'Diciembre'],
                monthsShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Set', 'Oct', 'Nov', 'Dic'],
                weekdays: ['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Domingo'],
                weekdaysAbbrev: ['L', 'Ma', 'Mi', 'J', 'V', 'S', 'D'],
                weekdaysShort: ['Lun', 'Mar', 'Mier', 'Jue', 'Vier', 'Sab', 'Dom']
            }
        });

      $(document).ready(function () {
            $('.collapsible').collapsible();
        });
</script>

{% endblock  %}

templates/calendario2.html
<!DOCTYPE html>

{% extends "base.html" %}

{% block extrahead %}
{{ form.media }}
{% endblock %}

{% load crispy_forms_tags %}
{% block content %}

<div id = "calendario_content">
  <div id = "calendario_header"><a>CALENDARIO</a></div>

<div class="row">
  <div class="col-md-4">

    <form  action="/search/trabajo" method="GET" >
      {{form|crispy}}
      <!--<button type="submit" class="btn btn-primary">Submit</button>-->
      <button type="submit" class="btn btn-success">
    <i class="icon-circle-arrow-right icon-large"></i> Ingresar
  </button>
    </form>
  </div>
</div>

<h2></h2>
<h2>TAREAS NOC</h2>
<div class="row">
    {%if tarealist%}
      <table class="table table-hover table-stripped">
        <thead>
          <th>Remedy</th>
          <th>Resumen </th>
          <th>Elemento de red afectado</th>
          <th>Duración</th>
          <th> Fecha de Inicio </th>
        </thead>

      {%for u in tarealist %}
      <tr>
        <td>{{u.remedy}}</td>
        <td>{{u.resumen}}</td>
        <td>{{u.elementoRed}}</td>
        <td>{{u.duration}}</td>
        <td>{{u.fechaInicio}}</td>


      </tr>
      {% endfor %}

    </table>
    {% else %}
    <div class="col-md-5">
      <p>No hay informacion que mostrar </p>



    {%endif%}

  </div>
</div>

</div>

{% endblock %}

templates/calendario_hfc.html
<!DOCTYPE html>

{% extends "base.html" %}

{% block extrahead %}
{{ form.media }}
{% endblock %}

{% load crispy_forms_tags %}
{% block content %}

<div class="row">
  <div class="col-md-4">

    <form  action="/search/trabajo_hfc" method="GET" >
      {{form|crispy}}
      <!--<button type="submit" class="btn btn-primary">Submit</button>-->
      <button type="submit" class="btn btn-success">
    <i class="icon-circle-arrow-right icon-large"></i> Ingresar
  </button>
    </form>
  </div>
</div>

<h2></h2>
<h2>TAREAS PLANTA</h2>
<div class="row">
    {%if tarealist %}

      <table class="table table-hover table-stripped">
        <thead>
          <th>Remedy</th>
          <th>Tipo de trabajo </th>
          <th>Elemento de red afectado</th>
          <th>Duración(hh:mm:ss)</th>
          <th> Fecha de Inicio </th>
        </thead>

      {%for u in tarealist %}
        {%if u.area == 'Planta' %}
      <tr>
        <td>{{u.infoPlanta.remedy}}</td>
        <td>{{u.infoPlanta.tipoTrabajo}}</td>
        <td> Troba-{{u.infoPlanta.troba.trobaNombre}}</td>
        <td>{{u.duration}} </td>
        <td>{{u.fecha}}</td>
      </tr>
        {%endif%}
      {% endfor %}

    </table>
    {% else %}
  <div class="col-md-5">
      <p>No hay informacion que mostrar </p>
    {%endif%}
  </div>

  <h2></h2>
<div class="col-md-6">
  <h2>TAREAS CORE</h2>
</div>

    {%if tarealist%}
      <table class="table table-hover table-stripped">
        <thead>
          <th>Remedy</th>
          <th>Grupo Coordinador </th>
          <th>Remitente</th>
          <th>Duración</th>
          <th>Zona de afectaccion </th>
          <th> Fecha de Inicio </th>
        </thead>

      {%for u in tarealist %}
      {%if u.area == 'Core' %}
      <tr>
        <td>{{u.infoCore.remedy}}</td>
        <td>{{u.infoCore.grupoCoordinador}}</td>
        <td>{{u.infoCore.remitente}}</td>
        <td>{{u.duration}}</td>
        <td>{{u.infoCore.site}}</td>
        <td>{{u.fecha}}</td>
      </tr>
        {% endif %}
      {% endfor %}

    </table>
    {% else %}
    <div class="col-md-5">
      <p>No hay informacion que mostrar </p>



    {%endif%}

  </div>
</div>

{% endblock %}

templates/form.html
<!DOCTYPE html>

{% extends "base.html" %}

{% block extrahead %}
{{ form.media }}
{% endblock %}

{% load crispy_forms_tags %}
{% crispy form  form.helper%}



{% block content %}
<div id = "form_content">
<div class="row">
  <div class="col-md-5">

    <form  method="post">
      {%csrf_token%}
      {{form|crispy}}
      <input type="submit" name="" value="Registrar">
      <!--<button type="submit" class="btn btn-primary">Submit</button>-->
    </form>

  </div>

</div>


</div>

{% endblock %}

templates/index.html
<!DOCTYPE html>
{% extends "base2.html" %}



{% block content %}
<div class="row">

    <div class = " col-md-12" id = "content_tra_pro">

          {%if tarealista%}
            <table class="table table-hover table-stripped">
              <thead>
                <th>Remedy</th>
                <th>Tipo de trabajo </th>
                <th>Elemento de red afectado </th>
                <th>Duración (hh:mm:ss)</th>
                <th> Fecha de Inicio </th>
                <th>Lista Usuarios</th>
              </thead>
            {%for t in tarealista%}
              {%if t.area == 'Planta' %}
            <tr>
              <td>{{t.infoPlanta.remedy}}</td>
              <td>{{t.infoPlanta.tipoTrabajo}}</td>
              <td> Troba-{{t.infoPlanta.troba.trobaNombre}}</td>
              <td>{{t.duration}}</td>
              <td>{{t.fecha}}</td>
              <td >
                <a  href="{% url 't_test:usuarios' t.infoPlanta.troba.trobaId  %}"><i class='fas fa-users' style='font-size:36px'></i></a>
              </td>
            </tr>
              {% endif %}
            {% endfor %}
          </table>
          {% else %}

          <div class="col-md-4"><p>no hay informacion que mostrar </p></div>
          {%endif%}
        </div>
</div>


{% endblock %}